[package]
name = "mry_macros"
version = "0.1.0"
edition = "2018"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["visit"] }

[lib]
proc-macro = true

[dev-dependencies]
similar-asserts = "1.1"
